import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Button from '@mui/material/Button'
import Card from '@mui/material/Card'
import { createTheme } from '@mui/material/styles'
import styles from '../styles/Home.module.css'
import { withTheme } from '@emotion/react'


export default function Languages() {
  return (
    <div className={styles.container}>
      <Head>
        <title> Data Structures</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Link href="/">
        <h1 className={styles.title}>
          ✨ algorithms ✨
        </h1>
        </Link>
        <p className={styles.subtitle}> how Python and C++ solve problems </p>
        <div className={styles.row}>
            <Card className={styles.card}>
                <h2>Intro to Algorithms</h2>
                <p>An <b>algorithm</b> is a set of steps for solving a problem.</p>
                <p>An algorithm takes <b>input</b> and produces <b>output</b>.</p><br/>
                <p>We measure the <b>time complexity</b> and <b>space complexity</b> of algorithms using <b>Big-O Notation</b>.</p>
            </Card>
        </div>
      </main>

      <footer className={styles.footer}>
        <p>powered by the tears of CS students</p>
      </footer>
    </div>
  )
}
