import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Button from '@mui/material/Button'
import Card from '@mui/material/Card'
import { createTheme } from '@mui/material/styles'
import styles from '../styles/Home.module.css'
import { withTheme } from '@emotion/react'


export default function Array() {
  return (
    <div className={styles.container}>
      <Head>
        <title> Data Structures</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <Link href="/">
        <h1 className={styles.title}>
          ✨ array ✨
        </h1>
        </Link>
        <Link href="/">
          <p className={styles.subtitle}> collection of data in contiguous memory locations</p>
        </Link>
        <div className={styles.column}>
            <Card className={styles.card}>
                <h2>Intro to Arrays</h2>
                <p>An <b>array</b> holds data "<b>elements</b>" in <b>contiguous memory</b> locations.</p>  
                <p>This is called a <b>linear</b> data structure because elements retain or manipulate their position relative to other elements.</p>
                <p>Common array-based data structures include <b>stacks</b> and <b>queues</b>.</p>
                <div className={styles.row}>
                  <Link href="/stack">
                    <Button className={styles.button}>Stack</Button>
                  </Link>
                  <Link href="/queue">
                    <Button className={styles.button}>Queue</Button>
                  </Link>
                </div>
            </Card>
            <h2>Implementation</h2>
            <div className={styles.row}>
              <Card className={styles.card}>
                <h2>Python</h2>
                <p>Python arrays are called <b>lists</b>.</p>
                  <br />
                  <div className={styles.code}>
                    <h2>array.py</h2>
                    <pre>
                      <code>
                        <p>class Stack:</p><br/>
                      </code>
                    </pre>
                  </div>
              </Card>
              <Card className={styles.card}>
                <h2>C++</h2>
              </Card>
            </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <p>powered by the tears of CS students</p>
      </footer>
    </div>
  )
}
