import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Button from '@mui/material/Button'
import Card from '@mui/material/Card'
import { createTheme } from '@mui/material/styles'
import styles from '../styles/Home.module.css'
import { withTheme } from '@emotion/react'


export default function Datastructures() {
  return (
    <div className={styles.container}>
      <Head>
        <title> Data Structures</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <Link href="/">
        <h1 className={styles.title}>
          ✨ data structures ✨
        </h1>
        </Link>
        <Link href="/languages">
          <p className={styles.subtitle}> what are data structures?</p>
        </Link>
        <div className={styles.row}>
            <Card className={styles.card}>
                <h2>Intro to Data Structures</h2>
                <p><b>Data Structures</b> are useful ways of storing data.</p>
                <p>An <b>Abstract Data Type</b> describes how data is stored and manipulated (but not its exact implementation).</p><br/>
                <p>Object-oriented languages like Python and C++ usually implement data structures as a <b>class</b> and their operations as the <b>class methods</b>.</p>
                <p>The most common data structures are <b>arrays</b> (or strings), <b>stacks</b>, <b>queues</b>, <b>linked lists</b>, <b>trees</b>, and <b>hash tables</b> (also called "hash maps").</p>
                <div className={styles.row}>
                    <Link href="/array">
                        <Button className={styles.button}>Array</Button>
                    </Link>
                    <Link href="/stack">
                        <Button className={styles.button}>Stack</Button>
                    </Link>
                    <Link href="/queue">
                        <Button className={styles.button}>Queue</Button>
                    </Link>
                    <Link href="/linkedlist">
                        <Button className={styles.button}>Linked List</Button>
                    </Link>
                    <Link href="/tree">
                        <Button className={styles.button}>Tree</Button>
                    </Link>
                    <Link href="/hashtable">
                        <Button className={styles.button}>Hash Table</Button>
                    </Link>
                </div>
            </Card>
        </div>
      </main>

      <footer className={styles.footer}>
        <p>powered by the tears of CS students</p>
      </footer>
    </div>
  )
}
