import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Button from '@mui/material/Button'
import Card from '@mui/material/Card'
import { createTheme } from '@mui/material/styles'
import styles from '../styles/Home.module.css'
import { withTheme } from '@emotion/react'


export default function Datastructures() {
  return (
    <div className={styles.container}>
      <Head>
        <title> Data Structures</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <Link href="/">
        <h1 className={styles.title}>
          ✨ data structures ✨
        </h1>
        </Link>
        <Link href="/languages">
          <p className={styles.subtitle}> what are data structures?</p>
        </Link>
        <div className={styles.row}>
            <Card className={styles.card}>
                <h2>Intro to Data Structures</h2>
                <p><b>Data Structures</b> are useful ways of storing data.  An <b>Abstract Data Type</b> describes how data is stored and manipulated (but not its exact implementation).</p>
                <Button>Stack</Button>
            </Card>
        </div>
      </main>

      <footer className={styles.footer}>
        <p>powered by the tears of CS students</p>
      </footer>
    </div>
  )
}
