import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Button from '@mui/material/Button'
import { createTheme } from '@mui/material/styles'
import styles from '../styles/Home.module.css'
import { withTheme } from '@emotion/react'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title> Data Structures</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          ✨ data structures and algorithms ✨
        </h1>
        <Link href="/languages">
          <p className={styles.subtitle}> in Python and C++</p>
        </Link>
        <div className={styles.row}>
          <Link href="/datastructures">
            <Button className={styles.button}>Data Structures</Button>
          </Link>
          <Link href="/algorithms">
            <Button className={styles.button}>Algorithms</Button>
          </Link>
        </div>
        <Link href="/languages"><Button className={styles.button}>About Python and C++</Button></Link>
      </main>

      <footer className={styles.footer}>
        <p>powered by the tears of CS students</p>
      </footer>
    </div>
  )
}
