import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Button from '@mui/material/Button'
import Card from '@mui/material/Card'
import { createTheme } from '@mui/material/styles'
import styles from '../styles/Home.module.css'
import { withTheme } from '@emotion/react'


export default function Languages() {
  return (
    <div className={styles.container}>
      <Head>
        <title> Data Structures</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Link href="/">
        <h1 className={styles.title}>
          ✨ languages ✨
        </h1>
        </Link>
        <p className={styles.subtitle}> why Python and C++?</p>
        <div className={styles.row}>
            <Card className={styles.card}>
                <h2>Python</h2>
                <p>Python is a high level programming language. Python is easier than C++ because it abstracts away lower level concerns like memory allocation and management.</p>
                <p></p>
            </Card>
            <Card className={styles.card}>
                <h2>C++</h2>
                <p>C++ is also a high level language, but it retains lower-level features like memory allocation and management.</p>
            </Card>
        </div>
      </main>

      <footer className={styles.footer}>
        <p>powered by the tears of CS students</p>
      </footer>
    </div>
  )
}
