import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Button from '@mui/material/Button'
import Card from '@mui/material/Card'
import { createTheme } from '@mui/material/styles'
import styles from '../styles/Home.module.css'
import { withTheme } from '@emotion/react'


export default function Languages() {
  return (
    <div className={styles.container}>
      <Head>
        <title> Data Structures</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Link href="/">
        <h1 className={styles.title}>
          ✨ languages ✨
        </h1>
        </Link>
        <p className={styles.subtitle}> why Python and C++?</p>
        <div className={styles.row}>
            <Card className={styles.card}>
                <h2>Python</h2>
                <p>Python is a simple high-level <b>object-oriented</b> programming language that makes coding easy. </p>
                <p>Python is <b>interpreted</b> rather than compiled.</p>
                <p>Python is distinguished by its use of <b>whitespace</b>. </p>
            </Card>
            <Card className={styles.card}>
                <h2>C++</h2>
                <p>C++ is also a high-level <b>object-oriented</b> language, but it retains lower-level features like <b>memory allocation and management</b> that make it <b> faster than Python</b>.</p>
                <p>C++ is <b>compiled</b> rather than interpreted; compiler <b>directives</b> in the file are preceded by <b>#</b> like so: <b>"#include {"<iostream>"}"</b></p>
                <p>C++ originated as an object-oriented extension to C (sometimes called "C with classes"). </p>
                <p>C++ uses <b>curly braces</b>, not whitespace.</p>
            </Card>
        </div>
      </main>

      <footer className={styles.footer}>
        <p>powered by the tears of CS students</p>
      </footer>
    </div>
  )
}
